project_id = "dxxfablfqigoewcfmjzl"

[functions.test-panel-connection]
verify_jwt = false

[functions.mundogf-discover]
verify_jwt = false

[functions.mundogf-renew]
verify_jwt = false

[functions.sigma-renew]
verify_jwt = false

[functions.koffice-renew]
verify_jwt = false

[functions.uniplay-renew]
verify_jwt = false